name: budgie-common-themes
title: Budgie Common Themes
build-base: core24
base: bare
version: '2025-05'
license: GPL-3.0
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Themes used by Ubuntu Budgie
description: |
  A Snap that allows you to use Ubuntu Budgie themes in Snap apps
grade: stable
confinement: strict

source-code:
  - https://github.com/UbuntuBudgie/pocillo
  - https://github.com/Kyuyrii/budgie-common-themes
website: https://ubuntubudgie.org/
issues: https://github.com/Kyuyrii/budgie-common-themes/issues

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Pocillo
        - $SNAP/share/icons/Pocillo-light
        - $SNAP/share/icons/TelaBudgie
        - $SNAP/share/icons/TelaBudgie-dark
        - $SNAP/share/icons/TelaBudgie-light
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Pocillo
        - $SNAP/share/gtk2/Pocillo-dark
        - $SNAP/share/gtk2/Pocillo-light
        - $SNAP/share/gtk2/Pocillo-slim
        - $SNAP/share/gtk2/Pocillo-slim-dark
        - $SNAP/share/gtk2/Pocillo-slim-light
        - $SNAP/share/gtk2/QogirBudgie
        - $SNAP/share/gtk2/QogirBudgie-Dark
        - $SNAP/share/gtk2/QogirBudgie-Light
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Pocillo
        - $SNAP/share/themes/Pocillo-dark
        - $SNAP/share/themes/Pocillo-light
        - $SNAP/share/themes/Pocillo-slim
        - $SNAP/share/themes/Pocillo-slim-dark
        - $SNAP/share/themes/Pocillo-slim-light
        - $SNAP/share/themes/QogirBudgie
        - $SNAP/share/themes/QogirBudgie-Dark
        - $SNAP/share/themes/QogirBudgie-Light
parts:
  icon-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/pocillo-icon-theme_0.21.1_all.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons/

  gtk-2-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_0.21.1_all.deb
    organize:
      usr/share/themes: share/gtk2
    prime:
      - share/gtk2/*/gtk-2.0

  gtk-3-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_0.21.1_all.deb
    organize:
      usr/share/themes: share/themes
    prime:
      - share/themes/*/gtk-3.0
      - share/themes/*/gtk-4.0
